---
- name: Deploy Docker Project
  hosts: your_target_hosts
  become: true

  vars:
    repo_url: "https://github.com/alkashara/PT_START2024.git"
    project_dir: "/opt/PT_START2024"

  tasks:
    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        update: yes

    - name: Change to project directory and bring up Docker Compose
      shell: |
        docker-compose up -d
      args:
        chdir: "{{ project_dir }}"
